#!/usr/bin/env bash

port=${PORT}

export ADDR=${port}

if [ -n "$NGROK_API_TOKEN" ]; then
  NGROK_OPTS="${NGROK_OPTS} --authtoken ${NGROK_API_TOKEN}"
fi

# Start the tunnel
if [ -f $PWD/ngrok_template.yml ]; then
  rm -f $PWD/ngrok.yml $PWD/temp.yml
  ( echo "cat << EOF > $PWD/ngrok.yml";
    cat $PWD/ngrok_template.yml;
    echo "";
    echo "EOF";
  ) >$PWD/temp.yml
  . $PWD/temp.yml
  cat $PWD/ngrok.yml
fi

if [ -f $PWD/ngrok.yml ]; then
    ngrok_cmd="ngrok start -config $PWD/ngrok.yml --all"
else
    ngrok_cmd=".heroku/bin/ngrok ${NGROK_COMMAND:-"http"} -log stdout --log-level debug ${NGROK_OPTS} ${port}"
fi

echo "Starting ngrok with command \`${ngrok_cmd}\`"
eval "$ngrok_cmd >/dev/null 2>&1 &"
ngrok_pid=$!

echo "HEROKU NGROK PID $ngrok_pid"

export NGROK_PID=$ngrok_pid

eval "$@"
exit $?
